CREATE TABLE IF NOT EXISTS authors (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS publications (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS words (
	word TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS categorys (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	precomputed_left INTEGER NOT NULL,
	precomputed_right INTEGER NOT NULL,
	UNIQUE (precomputed_left),
	UNIQUE (precomputed_right),
	CHECK (precomputed_left < precomputed_right)
);

CREATE TABLE IF NOT EXISTS keywords (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	cat_id INTEGER NOT NULL
		REFERENCES categorys (id)
			ON UPDATE CASCADE
			ON DELETE RESTRICT
			NOT DEFERRABLE,
	word TEXT NOT NULL
		REFERENCES words (word)
			ON UPDATE CASCADE
			ON DELETE RESTRICT
			NOT DEFERRABLE,
	UNIQUE (cat_id, word)
);

CREATE TABLE IF NOT EXISTS papers (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
-- Because sqlite stores dates as yyyy-mm-dd text
	pub_date TEXT NOT NULL,
	pub_id INTEGER
		REFERENCES publications (id)
			ON UPDATE CASCADE
			ON DELETE RESTRICT,
	cat_id INTEGER
		REFERENCES categorys (id)
			ON UPDATE CASCADE
			ON DELETE RESTRICT
			NOT DEFERRABLE
);

CREATE TABLE IF NOT EXISTS authored_by (
	author INTEGER NOT NULL
		REFERENCES authors (id)
			ON UPDATE CASCADE
			ON DELETE RESTRICT
			NOT DEFERRABLE,
	paper INTEGER NOT NULL
		REFERENCES papers (id)
			ON UPDATE CASCADE
			ON DELETE RESTRICT
			NOT DEFERRABLE,
	PRIMARY KEY (author, paper)
);

CREATE TABLE IF NOT EXISTS paper_refs (
	refers INTEGER NOT NULL
		REFERENCES papers (id)
			ON UPDATE CASCADE
			ON DELETE CASCADE
			NOT DEFERRABLE,
	refered_by INTEGER NOT NULL
		REFERENCES papers (id)
			ON UPDATE CASCADE
			ON DELETE CASCADE
			NOT DEFERRABLE
);

CREATE TABLE IF NOT EXISTS paper_keywords (
	paper INTEGER NOT NULL
		REFERENCES paper(id)
			ON DELETE CASCADE
			ON UPDATE CASCADE
			NOT DEFERRABLE,
	keyword INTEGER NOT NULL
		REFERENCES keywords (id)
			ON DELETE CASCADE
			ON UPDATE CASCADE
			NOT DEFERRABLE,
	PRIMARY KEY (paper, keyword)
);
